### ISSUE TITLE
Is it possible to create a network connection to a running vcontrold raspberry pi instance

### ISSUE THREAD

**Issue by compumark** [michelde/openv-vcontrold-docker#4]
Hi - I found your project via the Synology NAS Docker application and I wanted to start it there, but I didn succeeded in the first place. Before troubleshotting this, I want to know, if it is possible to grab the data also from a remote (same network) running raspberry pi with already configured vcontrold, running since a couple of years, instead of the local usb connection Thanks a lot,
Mark

**Comment by michelde** [comment]
Basically this would work as the vclient can also be configured to read the data from a vcontrol server other than localhost. See line: https://github.com/michelde/openv-vcontrold-docker/blob/56f76d04cc70ae8aafe46c63132a7f3c5f029250/startup.sh#L26

But of course you would need to change some things in the startup script.

**Comment by compumark** [comment]
Thanks a lot for the feedback. 
I actually got the docker running and copied my vito,xml and vacontrold.xml into the config folder. 
I then installed nano and modified the startup.sh and started it with . startup.sh again.
Every 90 seconds(which I set as interval) I see this error message: 

![image](https://user-images.githubusercontent.com/75847830/229828590-dd93909f-8982-46c5-bb1d-9791af3d1567.png)

Do you know what additional things need to be changed in the startup script to get this working? 
If I have this, I can try to make a copy of the repository and change it for my needs - never done that ;-) and I must see how I can get this than working in the Synology docker instance.

**Comment by michelde** [comment]
Why you're copying the xml files to the config folder? These are only needed for the vcontrold server. As you're just interested to read the values, you just need to focus on vclient --> https://github.com/openv/vcontrold/blob/master/doc/man/vclient.rst. Just get this running separately and you're almost good to go.
