### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by ghost** [michelde/openv-vcontrold-docker#6]
could some body point me the direction how to install this container? 
how do i handle my mqtt log in data?
is the compose yaml enough?

**Comment by michelde** [comment]
I think you would start to read the [documentation](https://docs.docker.com/compose/) about docker compose and then maybe get some tutorials to get an idea how this works. 
If there is anything missing in the README.md please feel free to create a pull request and add further information, which is missing.

**Comment by ghost** [comment]
not really helpful answer.
